/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-background": "var(--color-on-background)",
        "primary-fixed": "var(--color-primary-fixed)",
        "surface-container": "var(--color-surface-container)",
        "border-hairline-dark": "var(--color-border-hairline-dark)",
        "outline-variant": "var(--color-outline-variant)",
        "error-container": "var(--color-error-container)",
        tertiary: "var(--color-tertiary)",
        primary: "var(--color-primary)",
        outline: "var(--color-outline)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "accent-subtle": "var(--color-accent-subtle)",
        surface: "var(--color-surface)",
        "canvas-bg": "var(--color-canvas-bg)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "accent-hover": "var(--color-accent-hover)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        background: "var(--color-background)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "inverse-surface": "var(--color-inverse-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container-low": "var(--color-surface-container-low)",
        "secondary-container": "var(--color-secondary-container)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-error-container": "var(--color-on-error-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-variant": "var(--color-surface-variant)",
        "text-secondary": "var(--color-text-secondary)",
        "border-hairline": "var(--color-border-hairline)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "inverse-primary": "var(--color-inverse-primary)",
        secondary: "var(--color-secondary)",
        error: "var(--color-error)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-container": "var(--color-tertiary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "text-primary": "var(--color-text-primary)",
        "canvas-subtle": "var(--color-canvas-subtle)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-secondary": "var(--color-on-secondary)",
        "on-error": "var(--color-on-error)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "text-tertiary": "var(--color-text-tertiary)"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        margin: "2rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "display-hero": ["Inter"],
        "body-md": ["Inter"],
        "title-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-hero-mobile": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.035em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["17px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-hero-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
