/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "canvas-base": "#000000",
        "surface": "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1c1b1d",
        "surface-container": "#201f21",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "surface-card": "#121215",
        "surface-card-hover": "#16161a",
        "surface-elevated": "#1c1b1d",
        "surface-variant": "#353437",
        "surface-tint": "#c6c6c7",
        
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#c4c7c8",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        "outline": "#8e9192",
        "outline-variant": "#444748",

        primary: "#ffffff",
        "on-primary": "#2f3131",
        "primary-container": "#e2e2e2",
        "on-primary-container": "#636565",
        "inverse-primary": "#5d5f5f",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c7",
        "on-primary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#454747",

        secondary: "#abc7ff",
        "on-secondary": "#002f66",
        "secondary-container": "#0372e4",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#d7e2ff",
        "secondary-fixed-dim": "#abc7ff",
        "on-secondary-fixed": "#001b3f",
        "on-secondary-fixed-variant": "#00458f",

        tertiary: "#ffffff",
        "on-tertiary": "#1000a9",
        "tertiary-container": "#e1e0ff",
        "on-tertiary-container": "#4f51dd",
        "tertiary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed": "#07006c",
        "on-tertiary-fixed-variant": "#2f2ebe",

        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",

        background: "#131315",
        "on-background": "#e5e1e4",

        "text-primary": "#f5f5f7",
        "text-secondary": "#8e8e93",
        "text-muted": "#6e6e73",
        "text-tertiary": "#6e6e73",

        "hairline-border": "rgba(255, 255, 255, 0.08)",
        "hairline-border-bright": "rgba(255, 255, 255, 0.16)",
        "glass-surface": "rgba(20, 20, 24, 0.75)",
        "border-hairline": "rgba(255, 255, 255, 0.08)",
        "border-hairline-dark": "rgba(255, 255, 255, 0.08)",

        "apple-blue": "#2997FF",
        "apple-hover": "#147CE5"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.25rem",
        "gutter-lg": "2rem",
        margin: "1.5rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        code: ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        display: ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        code: ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
